site_name: Biblioteca para microcontroladores sAPI
pages:
- Introducción: index.md
- Principios de diseño: design-rules.md
- Tipos de datos: data-types.md
- Periféricos físicos: physical-ip-cores.md
- Periféricos externos y virtuales: virtual-ip-cores.md
- Utilización de la biblioteca: utilizacion.md
- Ejemplos: ejemplos.md
theme: readthedocs
